### ISSUE TITLE
Confirmation messages from wp rewrite structure appear in reverse order

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/rewrite-command#28]
Given the following command:

```
wp rewrite structure /%year%/%monthnum%/%postname%/
```

the output is:

```
Success: Rewrite rules flushed.
Success: Rewrite structure set.
```

One would expect that the new rewrite structure gets set before the rewrite rules are flushed (which does happen), but the confirmation message suggests the opposite.

Is there a way that this confirmation message can be improved?

**Comment by schlessera** [comment]
As the `WP_CLI::success()` method does not automatically exit, it is just a matter of moving line [169](https://github.com/wp-cli/rewrite-command/blob/master/src/Rewrite_Command.php#L169) further up in front of line [150](https://github.com/wp-cli/rewrite-command/blob/master/src/Rewrite_Command.php#L150).
