### ISSUE TITLE
Be able to flush the rewrite rules on all sites in a network

### ISSUE THREAD

**Issue by lukecav** [wp-cli/rewrite-command#45]
Currently it is not possible to flush the rewrite rules or to be able to use the --hard flag in multisites. Include a flag to be able to use `--network`.

Example
`wp rewrite flush --network`

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @lukecav

It's possible to achieve what you're looking for with [composition](https://make.wordpress.org/cli/handbook/contributions/philosophy/#composability-is-always-a-good-idea):

```
wp site list --field=url | xargs -n1 -I % wp --url=% rewrite flush
```
