### ISSUE TITLE
Why is the apache_modules config necessary?

### ISSUE THREAD

**Issue by arjenblokzijl** [wp-cli/rewrite-command#56]
Hi 👋 ,

I was wondering why the additional config `wp-cli.yml` or `config.yml` is [necessary](https://developer.wordpress.org/cli/commands/rewrite/flush/)? Can't this be passed as an argument? It feels cumbersome to add this config file to all our repos.

```
apache_modules:
  - mod_rewrite
 ```
 
 Would you welcome a PR? Thanks in advance 🙏 .

**Comment by schlessera** [comment]
To be honest, I completely ignore why that is a requirement in the first place. Just removing that check altogether would probably not cause any issues.

@danielbachhuber Do you maybe have some historical context here on why that command has such a weird check (and why the check's function is dynamically defined 😶) ?

**Comment by danielbachhuber** [comment]
> Do you maybe have some historical context here on why that command has such a weird check (and why the check's function is dynamically defined 😶) ?

@schlessera Here's the original PR: https://github.com/wp-cli/wp-cli/pull/563

It looks like core has some conditional on based on the return value of `apache_get_modules()`: https://github.com/WordPress/wordpress-develop/blob/55c34595d013ed02c1126a05ede66c1943ab72b3/src/wp-includes/functions.php#L5897-L5903

My guess is that the conditional function exists to trick WordPress into specific behavior when the `apache_get_modules()` function isn't available: https://stackoverflow.com/questions/3178173/alternatives-to-apache-get-modules-to-get-list-of-loaded-apache-modules

I suppose we could always define `apache_get_modules()` when `--hard` is used, although I have no idea what breakage might occur.

**Comment by danielbachhuber** [comment]
Let's leave things as they are for now.

**Comment by arjenblokzijl** [comment]
@danielbachhuber thanks for getting back on this. I currently have no need for this and apparently it doesn't show up that often.
